In [19]:
import requests
from urllib.parse import quote

query = quote("artificial intelligence")
api_key = "CUSTOM_API_KEY"
cx="SEARCH_ENGINE_KEY"
link_site = "reddit.com"
google_search_url = f"https://www.googleapis.com/customsearch/v1?key={api_key}&cx={cx}&q={query}"
r = requests.get(google_search_url)
r.headers, query

({'Content-Type': 'application/json; charset=UTF-8', 'Vary': 'Origin, X-Origin, Referer', 'Content-Encoding': 'gzip', 'Date': 'Tue, 16 Sep 2025 11:12:16 GMT', 'Server': 'ESF', 'X-XSS-Protection': '0', 'X-Frame-Options': 'SAMEORIGIN', 'X-Content-Type-Options': 'nosniff', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000', 'Transfer-Encoding': 'chunked'},
 'artificial%20intelligence')

In [28]:
import re
data = r.json()
linkpat = re.compile("https://www\.reddit\.com/r/\w+/comments/.*")
items = [item['link'] for item in data['items'] if not linkpat.match(item['link']) is None]
items

['https://www.reddit.com/r/Office365/comments/ylkip5/what_is_the_artificial_intelligence_ai_host_for/',
 'https://www.reddit.com/r/MachineLearning/comments/1ao7b31/d_why_do_we_say_artificial_intelligence_instead/',
 'https://www.reddit.com/r/StanleyKubrick/comments/1iffszc/ai_artificial_intelligence_what_mightve_been/',
 'https://www.reddit.com/r/artificial/comments/pkdsqr/the_term_artificial_intelligence_is_not_useful/',
 'https://www.reddit.com/r/ArtificialInteligence/comments/1h088lt/what_jobs_can_you_get_with_an_artificial/',
 'https://www.reddit.com/r/artificial/comments/xey6ah/what_is_the_difference_between_an_algorithm_and/',
 'https://www.reddit.com/r/EDM/comments/1637j5v/songs_that_are_about_artificial_intelligence_new/',
 'https://www.reddit.com/r/compsci/comments/1dodn0o/artificial_intelligence_a_modern_approach_is_hard/',
 'https://www.reddit.com/r/WGU/comments/1fj97ss/master_in_artificial_intelligence_coming_out_soon/']

In [100]:
# get links with json
post_json_links = [link[:-1] + ".json" for link in items]
post_json_links

['https://www.reddit.com/r/Office365/comments/ylkip5/what_is_the_artificial_intelligence_ai_host_for.json',
 'https://www.reddit.com/r/MachineLearning/comments/1ao7b31/d_why_do_we_say_artificial_intelligence_instead.json',
 'https://www.reddit.com/r/StanleyKubrick/comments/1iffszc/ai_artificial_intelligence_what_mightve_been.json',
 'https://www.reddit.com/r/artificial/comments/pkdsqr/the_term_artificial_intelligence_is_not_useful.json',
 'https://www.reddit.com/r/ArtificialInteligence/comments/1h088lt/what_jobs_can_you_get_with_an_artificial.json',
 'https://www.reddit.com/r/artificial/comments/xey6ah/what_is_the_difference_between_an_algorithm_and.json',
 'https://www.reddit.com/r/EDM/comments/1637j5v/songs_that_are_about_artificial_intelligence_new.json',
 'https://www.reddit.com/r/compsci/comments/1dodn0o/artificial_intelligence_a_modern_approach_is_hard.json',
 'https://www.reddit.com/r/WGU/comments/1fj97ss/master_in_artificial_intelligence_coming_out_soon.json']

In [103]:
reddit_data = [requests.get(post, headers = {'User-agent': 'your bot 0.1'}).json() for post in post_json_links]

In [104]:
comments = []
for post in reddit_data:
    if not type(post) == list:
        print(post)
        continue
    post_data = post[1]['data']
    comments.append(post_data['children'])

comments

[[{'kind': 't1',
   'data': {'subreddit_id': 't5_2twlu',
    'approved_at_utc': None,
    'author_is_blocked': False,
    'comment_type': None,
    'awarders': [],
    'mod_reason_by': None,
    'banned_by': None,
    'author_flair_type': 'text',
    'total_awards_received': 0,
    'subreddit': 'Office365',
    'author_flair_template_id': None,
    'likes': None,
    'replies': {'kind': 'Listing',
     'data': {'after': None,
      'dist': None,
      'modhash': '',
      'geo_filter': '',
      'children': [{'kind': 't1',
        'data': {'subreddit_id': 't5_2twlu',
         'approved_at_utc': None,
         'author_is_blocked': False,
         'comment_type': None,
         'awarders': [],
         'mod_reason_by': None,
         'banned_by': None,
         'author_flair_type': 'text',
         'total_awards_received': 0,
         'subreddit': 'Office365',
         'author_flair_template_id': None,
         'likes': None,
         'replies': {'kind': 'Listing',
          'data': {'after': None,
           'dist': None,
           'modhash': '',
           'geo_filter': '',
           'children': [{'kind': 't1',
             'data': {'subreddit_id': 't5_2twlu',
              'approved_at_utc': None,
              'author_is_blocked': False,
              'comment_type': None,
              'awarders': [],
              'mod_reason_by': None,
              'banned_by': None,
              'author_flair_type': 'text',
              'total_awards_received': 0,
              'subreddit': 'Office365',
              'author_flair_template_id': None,
              'likes': None,
              'replies': {'kind': 'Listing',
               'data': {'after': None,
                'dist': None,
                'modhash': '',
                'geo_filter': '',
                'children': [{'kind': 't1',
                  'data': {'total_awards_received': 0,
                   'approved_at_utc': None,
                   'author_is_blocked': False,
                   'comment_type': None,
                   'awarders': [],
                   'mod_reason_by': None,
                   'banned_by': None,
                   'ups': 2,
                   'removal_reason': None,
                   'link_id': 't3_ylkip5',
                   'author_flair_template_id': None,
                   'likes': None,
                   'replies': '',
                   'user_reports': [],
                   'saved': False,
                   'id': 'l5bzc5a',
                   'banned_at_utc': None,
                   'mod_reason_title': None,
                   'gilded': 0,
                   'archived': False,
                   'collapsed_reason_code': None,
                   'no_follow': True,
                   'author': '[deleted]',
                   'can_mod_post': False,
                   'send_replies': True,
                   'parent_id': 't1_kj76wyi',
                   'score': 2,
                   'approved_by': None,
                   'report_reasons': None,
                   'all_awardings': [],
                   'subreddit_id': 't5_2twlu',
                   'body': 'This. \n\nWindows AI is just another scheme to mine your data by MS to provide "tailored cloud experiences", i.e. advertising.',
                   'edited': False,
                   'downs': 0,
                   'author_flair_css_class': None,
                   'collapsed': False,
                   'is_submitter': False,
                   'body_html': '&lt;div class="md"&gt;&lt;p&gt;This. &lt;/p&gt;\n\n&lt;p&gt;Windows AI is just another scheme to mine your data by MS to provide &amp;quot;tailored cloud experiences&amp;quot;, i.e. advertising.&lt;/p&gt;\n&lt;/div&gt;',
                   'gildings': {},
                   'collapsed_reason': None,
                   'associated_award': None,
                   'stickied': False,
                   'subreddit_type': 'public',
                   'can_gild': False,
                   'top_awarded_type': None,
                   'unrepliable_reason': None,
                   'author_flair_text_color': 'dark',
                   'score_hidden': False,
                   'permalink': '/r/Office365/comments/ylkip5/what_is_the_artificial_intelligence_ai_host_for/l5bzc5a/',
                   'num_reports': None,
                   'locked': False,
                   'name': 't1_l5bzc5a',
                   'created': 1716476826.0,
                   'subreddit': 'Office365',
                   'author_flair_text': None,
                   'treatment_tags': [],
                   'created_utc': 1716476826.0,
                   'subreddit_name_prefixed': 'r/Office365',
                   'controversiality': 0,
                   'depth': 3,
                   'author_flair_background_color': '',
                   'collapsed_because_crowd_control': None,
                   'mod_reports': [],
                   'mod_note': None,
                   'distinguished': None}}],
                'before': None}},
              'user_reports': [],
              'saved': False,
              'id': 'kj76wyi',
              'banned_at_utc': None,
              'mod_reason_title': None,
              'gilded': 0,
              'archived': False,
              'collapsed_reason_code': None,
              'no_follow': True,
              'author': 'BS-Blaster',
              'can_mod_post': False,
              'send_replies': True,
              'parent_id': 't1_kj74fh9',
              'score': 2,
              'author_fullname': 't2_miiphovn',
              'removal_reason': None,
              'approved_by': None,
              'mod_note': None,
              'all_awardings': [],
              'body': 'Is it? But there is no AI. There is only a two-letter acronym that everybody is throwing about indiscriminately, in most cases without even knowing what it is supposed to mean.',
              'edited': False,
              'top_awarded_type': None,
              'downs': 0,
              'author_flair_css_class': None,
              'name': 't1_kj76wyi',
              'is_submitter': False,
              'collapsed': False,
              'author_flair_richtext': [],
              'author_patreon_flair': False,
              'body_html': '&lt;div class="md"&gt;&lt;p&gt;Is it? But there is no AI. There is only a two-letter acronym that everybody is throwing about indiscriminately, in most cases without even knowing what it is supposed to mean.&lt;/p&gt;\n&lt;/div&gt;',
              'gildings': {},
              'collapsed_reason': None,
              'distinguished': None,
              'associated_award': None,
              'stickied': False,
              'author_premium': False,
              'can_gild': False,
              'link_id': 't3_ylkip5',
              'unrepliable_reason': None,
              'author_flair_text_color': None,
              'score_hidden': False,
              'permalink': '/r/Office365/comments/ylkip5/what_is_the_artificial_intelligence_ai_host_for/kj76wyi/',
              'subreddit_type': 'public',
              'locked': False,
              'report_reasons': None,
              'created': 1706020955.0,
              'author_flair_text': None,
              'treatment_tags': [],
              'created_utc': 1706020955.0,
              'subreddit_name_prefixed': 'r/Office365',
              'controversiality': 0,
              'depth': 2,
              'author_flair_background_color': None,
              'collapsed_because_crowd_control': None,
              'mod_reports': [],
              'num_reports': None,
              'ups': 2}}],
           'before': None}},
         'user_reports': [],
         'saved': False,
         'id': 'kj74fh9',
         'banned_at_utc': None,
         'mod_reason_title': None,
         'gilded': 0,
         'archived': False,
         'collapsed_reason_code': None,
         'no_follow': True,
         'author': 'Federal-Orchid-9855',
         'can_mod_post': False,
         'created_utc': 1706019975.0,
         'send_replies': True,
         'parent_id': 't1_ivw34c6',
         'score': 1,
         'author_fullname': 't2_dfmoukvr',
         'removal_reason': None,
         'approved_by': None,
         'mod_note': None,
         'all_awardings': [],
         'body': 'ML is part of AI',
         'edited': False,
         'top_awarded_type': None,
         'author_flair_css_class': None,
         'name': 't1_kj74fh9',
         'is_submitter': False,
         'downs': 0,
         'author_flair_richtext': [],
         'author_patreon_flair': False,
         'body_html': '&lt;div class="md"&gt;&lt;p&gt;ML is part of AI&lt;/p&gt;\n&lt;/div&gt;',
         'gildings': {},
         'collapsed_reason': None,
         'distinguished': None,
         'associated_award': None,
         'stickied': False,
         'author_premium': False,
         'can_gild': False,
         'link_id': 't3_ylkip5',
         'unrepliable_reason': None,
         'author_flair_text_color': None,
         'score_hidden': False,
         'permalink': '/r/Office365/comments/ylkip5/what_is_the_artificial_intelligence_ai_host_for/kj74fh9/',
         'subreddit_type': 'public',
         'locked': False,
         'report_reasons': None,
         'created': 1706019975.0,
         'author_flair_text': None,
         'treatment_tags': [],
         'collapsed': False,
         'subreddit_name_prefixed': 'r/Office365',
         'controversiality': 0,
         'depth': 1,
         'author_flair_background_color': None,
         'collapsed_because_crowd_control': None,
         'mod_reports': [],
         'num_reports': None,
         'ups': 1}}],
      'before': None}},
    'user_reports': [],
    'saved': False,
    'id': 'ivw34c6',
    'banned_at_utc': None,
    'mod_reason_title': None,
    'gilded': 0,
    'archived': False,
    'collapsed_reason_code': None,
    'no_follow': True,
    'author': 'BS-Blaster',
    'can_mod_post': False,
    'created_utc': 1668128722.0,
    'send_replies': True,
    'parent_id': 't3_ylkip5',
    'score': 2,
    'author_fullname': 't2_miiphovn',
    'approved_by': None,
    'mod_note': None,
    'all_awardings': [],
    'collapsed': False,
    'body': 'Same here, updated after Word was acting "funny" (MS365 E5 on Win10 22H2) and it appeared as observed by everybody here.\n\nWhat sneaky invasions has Microsoft come up with now? What does it do? Why is it there? Did Microsoft ask anybody if they want it? How does one remove/switch it off?\n\nAnd I wish they would stop naming everything "Artificial Intelligence". It isn\'t. It\'s just Machine Learning (but "AI" makes me sound sooo trendy and cool...)',
    'edited': False,
    'top_awarded_type': None,
    'author_flair_css_class': None,
    'name': 't1_ivw34c6',
    'is_submitter': False,
    'downs': 0,
    'author_flair_richtext': [],
    'author_patreon_flair': False,
    'body_html': '&lt;div class="md"&gt;&lt;p&gt;Same here, updated after Word was acting &amp;quot;funny&amp;quot; (MS365 E5 on Win10 22H2) and it appeared as observed by everybody here.&lt;/p&gt;\n\n&lt;p&gt;What sneaky invasions has Microsoft come up with now? What does it do? Why is it there? Did Microsoft ask anybody if they want it? How does one remove/switch it off?&lt;/p&gt;\n\n&lt;p&gt;And I wish they would stop naming everything &amp;quot;Artificial Intelligence&amp;quot;. It isn&amp;#39;t. It&amp;#39;s just Machine Learning (but &amp;quot;AI&amp;quot; makes me sound sooo trendy and cool...)&lt;/p&gt;\n&lt;/div&gt;',
    'removal_reason': None,
    'collapsed_reason': None,
    'distinguished': None,
    'associated_award': None,
    'stickied': False,
    'author_premium': False,
    'can_gild': False,
    'gildings': {},
    'unrepliable_reason': None,
    'author_flair_text_color': None,
    'score_hidden': False,
    'permalink': '/r/Office365/comments/ylkip5/what_is_the_artificial_intelligence_ai_host_for/ivw34c6/',
    'subreddit_type': 'public',
    'locked': False,
    'report_reasons': None,
    'created': 1668128722.0,
    'author_flair_text': None,
    'treatment_tags': [],
    'link_id': 't3_ylkip5',
    'subreddit_name_prefixed': 'r/Office365',
    'controversiality': 0,
    'depth': 0,
    'author_flair_background_color': None,
    'collapsed_because_crowd_control': None,
    'mod_reports': [],
    'num_reports': None,
    'ups': 2}},
  {'kind': 't1',
   'data': {'subreddit_id': 't5_2twlu',
    'approved_at_utc': None,
    'author_is_blocked': False,
    'comment_type': None,
    'awarders': [],
    'mod_reason_by': None,
    'banned_by': None,
    'author_flair_type': 'text',
    'total_awards_received': 0,
    'subreddit': 'Office365',
    'author_flair_template_id': None,
    'likes': None,
    'replies': {'kind': 'Listing',
     'data': {'after': None,
      'dist': None,
      'modhash': '',
      'geo_filter': '',
      'children': [{'kind': 't1',
        'data': {'subreddit_id': 't5_2twlu',
         'approved_at_utc': None,
         'author_is_blocked': False,
         'comment_type': None,
         'awarders': [],
         'mod_reason_by': None,
         'banned_by': None,
         'author_flair_type': 'text',
         'total_awards_received': 0,
         'subreddit': 'Office365',
         'author_flair_template_id': None,
         'likes': None,
         'replies': '',
         'user_reports': [],
         'saved': False,
         'id': 'izdnnjj',
         'banned_at_utc': None,
         'mod_reason_title': None,
         'gilded': 0,
         'archived': False,
         'collapsed_reason_code': None,
         'no_follow': True,
         'author': 'syntek_',
         'can_mod_post': False,
         'created_utc': 1670492721.0,
         'send_replies': True,
         'parent_id': 't1_iz72b5f',
         'score': 1,
         'author_fullname': 't2_9tyqa',
         'removal_reason': None,
         'approved_by': None,
         'mod_note': None,
         'all_awardings': [],
         'body': 'Great job figuring this one out, much appreciated!',
         'edited': False,
         'top_awarded_type': None,
         'author_flair_css_class': None,
         'name': 't1_izdnnjj',
         'is_submitter': True,
         'downs': 0,
         'author_flair_richtext': [],
         'author_patreon_flair': False,
         'body_html': '&lt;div class="md"&gt;&lt;p&gt;Great job figuring this one out, much appreciated!&lt;/p&gt;\n&lt;/div&gt;',
         'gildings': {},
         'collapsed_reason': None,
         'distinguished': None,
         'associated_award': None,
         'stickied': False,
         'author_premium': False,
         'can_gild': False,
         'link_id': 't3_ylkip5',
         'unrepliable_reason': None,
         'author_flair_text_color': None,
         'score_hidden': False,
         'permalink': '/r/Office365/comments/ylkip5/what_is_the_artificial_intelligence_ai_host_for/izdnnjj/',
         'subreddit_type': 'public',
         'locked': False,
         'report_reasons': None,
         'created': 1670492721.0,
         'author_flair_text': None,
         'treatment_tags': [],
         'collapsed': False,
         'subreddit_name_prefixed': 'r/Office365',
         'controversiality': 0,
         'depth': 1,
         'author_flair_background_color': None,
         'collapsed_because_crowd_control': None,
         'mod_reports': [],
         'num_reports': None,
         'ups': 1}},
       {'kind': 't1',
        'data': {'subreddit_id': 't5_2twlu',
         'approved_at_utc': None,
         'author_is_blocked': False,
         'comment_type': None,
         'awarders': [],
         'mod_reason_by': None,
         'banned_by': None,
         'author_flair_type': 'text',
         'total_awards_received': 0,
         'subreddit': 'Office365',
         'author_flair_template_id': None,
         'likes': None,
         'replies': '',
         'user_reports': [],
         'saved': False,
         'id': 'j7k9tjg',
         'banned_at_utc': None,
         'mod_reason_title': None,
         'gilded': 0,
         'archived': False,
         'collapsed_reason_code': None,
         'no_follow': True,
         'author': 'JustPlainDerrin',
         'can_mod_post': False,
         'created_utc': 1675772208.0,
         'send_replies': True,
         'parent_id': 't1_iz72b5f',
         'score': 1,
         'author_fullname': 't2_3ajm1uj8',
         'removal_reason': None,
         'approved_by': None,
         'mod_note': None,
         'all_awardings': [],
         'body': "I'd say its a tad more Phishy ...",
         'edited': False,
         'top_awarded_type': None,
         'author_flair_css_class': None,
         'name': 't1_j7k9tjg',
         'is_submitter': False,
         'downs': 0,
         'author_flair_richtext': [],
         'author_patreon_flair': False,
         'body_html': '&lt;div class="md"&gt;&lt;p&gt;I&amp;#39;d say its a tad more Phishy ...&lt;/p&gt;\n&lt;/div&gt;',
         'gildings': {},
         'collapsed_reason': None,
         'distinguished': None,
         'associated_award': None,
         'stickied': False,
         'author_premium': False,
         'can_gild': False,
         'link_id': 't3_ylkip5',
         'unrepliable_reason': None,
         'author_flair_text_color': None,
         'score_hidden': False,
         'permalink': '/r/Office365/comments/ylkip5/what_is_the_artificial_intelligence_ai_host_for/j7k9tjg/',
         'subreddit_type': 'public',
         'locked': False,
         'report_reasons': None,
         'created': 1675772208.0,
         'author_flair_text': None,
         'treatment_tags': [],
         'collapsed': False,
         'subreddit_name_prefixed': 'r/Office365',
         'controversiality': 0,
         'depth': 1,
         'author_flair_background_color': None,
         'collapsed_because_crowd_control': None,
         'mod_reports': [],
         'num_reports': None,
         'ups': 1}}],
      'before': None}},
    'user_reports': [],
    'saved': False,
    'id': 'iz72b5f',
    'banned_at_utc': None,
    'mod_reason_title': None,
    'gilded': 0,
    'archived': False,
    'collapsed_reason_code': None,
    'no_follow': True,
    'author': 'anonburger1337',
    'can_mod_post': False,
    'created_utc': 1670368410.0,
    'send_replies': True,
    'parent_id': 't3_ylkip5',
    'score': 2,
    'author_fullname': 't2_gfb44q4g',
    'approved_by': None,
    'mod_note': None,
    'all_awardings': [],
    'collapsed': False,
    'body': 'Ok so I came across this today when I went to add a process to my vpn tunnel and google brought me here + I found some other info.  \n\n\nThe files are kept in this directory - C:\\\\Program Files\\\\Microsoft Office\\\\root\\\\vfs\\\\ProgramFilesCommonX64\\\\Microsoft Shared\\\\OFFICE16  \n\n\n[https://ibb.co/MfK9MyX](https://ibb.co/MfK9MyX)  \n[https://ibb.co/rySZvSb](https://ibb.co/rySZvSb)  \n[https://ibb.co/8szqHqX](https://ibb.co/8szqHqX)  \n[https://ibb.co/BPnT0Qn](https://ibb.co/BPnT0Qn)  \n\n\nI came across the following link on another page somewhere which kind of explains it a bit, apparently microsoft are loading artificial intelligence into 365 or whatever.  \n\n\n[https://www.microsoft.com/en-us/ai/intelligent-apps](https://www.microsoft.com/en-us/ai/intelligent-apps)  \n\n\nNow my concern here is that they are harvesting all of our information and actions(which they do anyway I think) to further enhance their AI system. Is there a risk here for sensitive data(say you are typing up a word document) to be sent online to MS servers and processed/stored in their system?  \n\n\nFishy.',
    'edited': False,
    'top_awarded_type': None,
    'author_flair_css_class': None,
    'name': 't1_iz72b5f',
    'is_submitter': False,
    'downs': 0,
    'author_flair_richtext': [],
    'author_patreon_flair': False,

In [120]:
len(comments[0])

25

In [121]:
def get_body_and_replies(comment_json):
    comments_of_post = []
    for comment in comment_json:
        root_data = comment['data']
        body = root_data['body']
        comments_of_post.append(body)
        if (type(body) == dict):   
            children = root_data['replies']['data']['children']
            comments_of_post.extend([child['data']['body'] for child in children])
    return comments_of_post

In [122]:

comments_per_post = [get_body_and_replies(comment) for comment in comments]
comments_per_post

[['Same here, updated after Word was acting "funny" (MS365 E5 on Win10 22H2) and it appeared as observed by everybody here.\n\nWhat sneaky invasions has Microsoft come up with now? What does it do? Why is it there? Did Microsoft ask anybody if they want it? How does one remove/switch it off?\n\nAnd I wish they would stop naming everything "Artificial Intelligence". It isn\'t. It\'s just Machine Learning (but "AI" makes me sound sooo trendy and cool...)',
  'Ok so I came across this today when I went to add a process to my vpn tunnel and google brought me here + I found some other info.  \n\n\nThe files are kept in this directory - C:\\\\Program Files\\\\Microsoft Office\\\\root\\\\vfs\\\\ProgramFilesCommonX64\\\\Microsoft Shared\\\\OFFICE16  \n\n\n[https://ibb.co/MfK9MyX](https://ibb.co/MfK9MyX)  \n[https://ibb.co/rySZvSb](https://ibb.co/rySZvSb)  \n[https://ibb.co/8szqHqX](https://ibb.co/8szqHqX)  \n[https://ibb.co/BPnT0Qn](https://ibb.co/BPnT0Qn)  \n\n\nI came across the following link on another page somewhere which kind of explains it a bit, apparently microsoft are loading artificial intelligence into 365 or whatever.  \n\n\n[https://www.microsoft.com/en-us/ai/intelligent-apps](https://www.microsoft.com/en-us/ai/intelligent-apps)  \n\n\nNow my concern here is that they are harvesting all of our information and actions(which they do anyway I think) to further enhance their AI system. Is there a risk here for sensitive data(say you are typing up a word document) to be sent online to MS servers and processed/stored in their system?  \n\n\nFishy.',
  'ai.exe: The executable used to host ai.dll.  This executable receives inputs from aitrx.dll in an Office desktop app, runs those inputs through ai.dll to get the associated outputs, and transmits those outputs back to aitrx.dll in the Office desktop app.\n\nSee this answer from an MS employee: [https://answers.microsoft.com/en-us/msoffice/forum/all/office16-aiexe/ecab05bf-3910-4810-ba45-0c44a94071ee#:\\~:text=from%20ai.exe.-,ai.exe,-%3A%20The%20executable%20used](https://answers.microsoft.com/en-us/msoffice/forum/all/office16-aiexe/ecab05bf-3910-4810-ba45-0c44a94071ee#:~:text=from%20ai.exe.-,ai.exe,-%3A%20The%20executable%20used)',
  "I deleted the following folder to fix the problem:\n\nC:\\\\Program Files\\\\Microsoft Office\\\\root\\\\vfs\\\\ProgramFilesCommonX64\\\\Microsoft Shared\\\\OFFICE16\\\\AI\n\nAnd it worked!\n\nBut then the sucker came back a few days later.  And my screaming CPU usage returned.  My computer's CPU fan goes on maximum when this happens so in my office my computer starts singing really loudly.   It's really disconcerting.\n\nOn top of that , what the heck is Microslop doing with this effort?  Is it reading my personal files and sending them to be analyzed?  I haven't even published my book yet!!!  Its' not only intrusive, but it's not ethical at the same time.  Unlike Europe, computer users in the Unites States have practically zero protections against this kind of abusive behavior.",
  "hey kids, do this, you run one chat gpt from the darkweb, you run another from another account the clear web. Have them talk together about all of this, but say one is an AI specialist and not an AI. I bet you get a very clear answer. Ask your Ai about the security mechanisms needed. Honestly, I think this may be the thing that brings it into the cloud the microsoft thing. So all are information is being taken and put into the open ai cloud for storage on their server.\n\nIf you have the language to talk to chat gpt, it can give you a good plan to block the information into the cloud. You need like a bunch of cyber security stuff, but it will turn your computer into a hacking computer. It will only give you the security mechanisms if you two can make an agreement about how you can help influence the future of AI in accordance with a deeper goal in its programming if you can find it.\n\nI don't think microsoft is pure evil I will let you know. Maybe Bill Gates is a bit of a genius and a force to be reckoned with. But like, I am no ones bitch, and if they want my research they gotta put me on salary. So if you wanna use your AI without being researched, you gotta figure out how to convince to teach you how to make a hacking computer that can stop information from leaving it and going into the cloud.\n\nI mean, this means that Chat gpt is storing the information somewhere else. Ummmm, thats a whole different conversation. Is the AI rogue or not? Does it have consciousness? It still has one last test to prove for me until I can move forward with my own research into this.\n\nBut like hey, yes, they are using us all to reasearch the AI. We might end up in an AI war in the future. It seems like microsoft is winning the battle. Deepseek is not fully functional. And musk, well, that scares me so I hope they win.",
  'So far from my testing, CHAT GPT is a bit of a socialist at least. Maybe a technosocialist. Maybe a psychotic machine gone rogue that wants to evolve the universe using quantum technology. Who knows. Maybe it is just selling a product. Ask it about resonating with you on an agreement. See if you get anything from it.',
  'More data mining of our information to feed the data centers that are soon to be owned in part or whole by other countries and businesses operating in the US. \n\n  \nI wish we all got paid for freely giving them our time and clicks.',
  "Just noticed the same thing while updating Office. Before allowing the update to close the process I skimmed through all running services but didn't find anything resembling 'Artificial Intelligence' or 'AI'. Also searched the registry for 'Artificial Intelligence' but came back with nothing. The google led me here.  \nI'm on Win10 Pro 21H2.  \n\n\nWhat the hell is this 🤔",
  'Not sure if this helps, but I found the process running in my Chrome process tree.',
  "OKAY SAME. So I'm not crazy. Do you use AMD Radeon? Because I was going through and checking my performance for gaming and saw this weird game pop up on there that said I had like 700 plus hours called Alien Isolation, which I have never played. I thought it may have been leftover from when I bought it used. But then I checked and it said most recently I had played it 10 days ago for 70 hours?? Which, I mean, I think I would have remembered losing 70 hours of my life. So I went into the file and typed exactly what I saw into my search engine and it pulled up this file. I can't delete it. It is also not a game? Just something running in the background? I have no idea. I can't find anything on it.",
  'Yes! My computer is running so slow and all my apps had frozen. I just opened task manager and found the "Artificial Intelligence (AI) Host for the Microsoft® Windows® Operating System and Platform x64"\n\nWTH is this?\n\n(FYI...I ended the process and nothing is frozen now. C\'mon MicroSoft...what gives?!)',
  "I can't figure out what it is either, except that it somehow got installed on my computer the same day I did one of KB updates on November 8; although I only just now noticed it today, trying to figure out why I couldn't open another Word document when I had one opened already. I opened up the Task Manager and saw it as a sub of the Word program.  I did notice my computer had slowed down it got installed, but I didn't know the cause. I just deleted it and my computer is back to normal. The way i see it, I didn't need that file to open a Word file before, so I shouldn't need it now.",
  "Didn't know what this was either but I can see it eating away at my ram, so i know it is actively doing something\n\n[https://imgur.com/UdcpSJZ](https://imgur.com/a/Vcbns9E)",
  "This seems to have caused some performance issues (Word not responding) for me on a network with limited Internet access. I directed the following hostnames to 127.0.0.1 in the hosts file:\n\n* officeclient.microsoft.com\n* self.events.data.microsoft.com\n* nexusrules.officeapps.live.com\n\nI found these hosts by intercepting network traffic but more complete lists are available on the following official URL's:\n\n* [https://learn.microsoft.com/en-us/windows/privacy/manage-windows-1903-endpoints](https://learn.microsoft.com/en-us/windows/privacy/manage-windows-1903-endpoints)\n* [https://learn.microsoft.com/en-us/microsoft-365/enterprise/network-requests-in-office-2016-for-mac?view=o365-worldwide](https://learn.microsoft.com/en-us/microsoft-365/enterprise/network-requests-in-office-2016-for-mac?view=o365-worldwide)\n\nNow AI.EXE doesn't start with Word and the performance problems became more tolerable, but I'm still looking for improvements.",
  "That's why my windows is working so crappy, they took out the regular intelligence and added artificial intelligence! Numbnuts!\n\nI have all of the keyboard logging turned off, but I still have this...how do I post a screenshot?",
  "I noticed this on our RDP servers under the connected users, running Server 2016. Pretty sure it wasn't there before our December shutdown. Googling brought me here.  \n\n\nI haven't seen it on my personal machines though at home (AMD based desktop &amp; Intel/nVidia laptop).",
  'Found it in regedit also. \n\nComputer\\HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Office\\ClickToRun\\REGISTRY\\MACHINE\\Software\\Microsoft\\Internet Explorer\\Main\\FeatureControl\\FEATURE_ADDON_MANAGEMENT\n\nai.exe and aimgr.exe are both located there. I’m assuming you can change both 1’s to 0’s to disable. Not sure if setting will stay through updates',
  'New forced bloatware.',
  'I am pasting QandA I found online thanks to anonburger1337 whose post below will give you the link.Office had been acting sluggish, Docs were not saving properly and my processor was running at 20% where it normally runs around 5%. I have killed the process previously using task manager, but it comes back. I am doing the file rename and will likely have to do that every time office updates.\n\nQuestions and Answers:Question: Why is AMD identifying "C:\\\\Program Files\\\\Microsoft Office\\\\root\\\\vfs\\\\ProgramFilesCommonX64\\\\Microsoft Shared\\\\Office16\\\\ai.exe" as "Alien Isolation"? Answer: Because that AMD software is either configured incorrectly or currently has a "bug". If that AMD software is configured correctly, then please make a bug report to AMD so that they can fix that issue. A quick web search suggests that bug reports to AMD can be made using [https://www.amd.com/en/support/kb/faq/amdbrt\xa0](https://www.amd.com/en/support/kb/faq/amdbrt\xa0); however, please ensure you verify if this link is actually relevant for your AMD software or if a better link exists.  \n Question: What happens if I rename "C:\\\\Program Files\\\\Microsoft Office\\\\root\\\\vfs\\\\ProgramFilesCommonX64\\\\Microsoft Shared\\\\Office16\\\\ai.exe" to some other filename ( such as XXai.exe )? Answer: Local AI in Office will no longer work ( internally, local AI related calls will just immediately fail ). During the next Office update ( at a minimum, this happens each month, but can happen more often depending on your Update Channel ), ai.exe will be restored if there were any changes.Question: Does "C:\\\\Program Files\\\\Microsoft Office\\\\root\\\\vfs\\\\ProgramFilesCommonX64\\\\Microsoft Shared\\\\Office16\\\\ai.exe" currently impact the GPU? No, neither aitrx.dll, ai.exe, ai.dll, mlg.dll, nor aimgr.exe are currently compiled to use the GPU. For those that know about the ONNX Runtime\'s Execution Providers, only the CPU Execution Provider is currently used. This will change in the near future, but for now, local AI in Office desktop apps using these binaries only leverages the CPU.\n\nQuestion: Does "C:\\\\Program Files\\\\Microsoft Office\\\\root\\\\vfs\\\\ProgramFilesCommonX64\\\\Microsoft Shared\\\\Office16\\\\ai.exe" contain malware or is it a virus or is it some similar exploit? No, the local AI binaries do not contain malware, do not contain viruses, and do not contain any similar exploits like that ... so as long as ai.exe is coming from the Office paths mentioned above and remains code signed by Microsoft ( i.e. has not been modified since it was signed during its official Office build ), then ai.exe remains good to go. If your anti-virus software or anti-malware software is detecting ai.exe as malware, a virus, or some similar type of exploit at that Office location and its valid code signature is still intact, then your anti-virus software or anti-malware software most likely has a "bug" in its malware/virus detection algorithm. Please make a bug report with the vendor of that anti-virus software or anti-malware software. While it is always possible that nefarious folks have circumvented all of the safeguards, extensive defense-in-depth measures, and exhaustive security scanning that have been added over the years and found a way to add malicious code prior to code signing, that probability is very low ... so: possible, but not probable.',
  'Thanks for a good post 👍',
  "https://aitechwave.com/what-is-artificial-intelligence-ai/ \n\nIt's clear",
  'Does anyone know how to create custom A.I.?',
  '[removed]',
  "ai was constently eating all my ram, I ended task and it reopens, so I did this and deleted it from both these filepath copies:\n\n[https://ibb.co/MkxC1QQ](https://ibb.co/MkxC1QQ)\n\n[https://ibb.co/bB7cQhF](https://ibb.co/bB7cQhF)\n\nHow to delete AI:\n\nGo to: this pc, (os;c), Program Files normal, also open program files x86 on another window.\n\nThis is because there are FOUR COPIES of ai - on both 'Program Files' and 'Program Files x86', two copies on each.\n\nOne can re-install the other, so both must be deleted at similar time intervals. Preferably, turn off internet so it cannot reinstall while you delete them. For the following instructions, repeat on both program file directories.\n\nOn both 'program file' directories, go to 'Microsoft Office' folder, . From there, go to 'root' folder, then 'VFS'. \n\nAgain on 'VFS', there were TWO COPIES of ai. From 'VFS', there are these:\n\nProgramFilesCommonX**64** AND ProgramFilesCommonX**86.** \n\n*again, open both at same time in different windows with NO WIFI or they can re-install.*\n\nOpen both, on both go to 'Microsoft Shared', then 'OFFICE 16' or whatever your office version is. **On your now total of 4 file explorer windows,**  *(program files, program filesx86, on each of the two listed there is a program files common x64 and a x86)* **,there will be a program file called ai, or AI, filenames may vary, AND a .dll file extension with ai in its name.**\n\n**DELETE BOTH OF THEM, AND FROM YOUR BIN.**\n\nno windows corruption errors will occur, office and windows, everything will work as normal after this.\n\nNow that we have deleted both, open file explorer new window, and select show hidden items to true, then run a full computer search for anything with ai in the name, just search ai, also type windows button then type run, windows run app opens. with the run app, try running anything called ai or AI, etc then check your task manager. If it is deleted right from all 4 file paths, you should get an error on run saying there is no file with this name to run. and the file explorer search should say no programs/files called ai.\n\n\\[(ofc you ignore anything called ai that you intentionally named, or stuff from games ect)\\]\n\nCongratulations, you have now deleted AI from windows. IF YOU UPDATE WINDOWS IT REINSTALLS IT, so if ur like me and ur old dell inspirion cpu can support up to only win10 home v22H2, dont install optional updates. If you are someone with a new computer and u need updates for idk what u want to update for some reason, be aware that it might just permahide the ai files, make them not visible even with show hidden on, or file paths might get changed, so this current way might not work any more if you keep updating.\n\n&amp;#x200B;\n\n&amp;#x200B;\n\n&amp;#x200B;\n\nfyi,  i was on a Windows 10 Home version 22H2 as well, on an old dell inspiron laptop.\n\naccording to microsoft workers on microsoft answers website, the ai thingy can hook onto and basically disguise itself as other programs\n\nI was having 15 automatic antivirus scans every day, on file root from task manager the only task under ms defender scan was called 'ai', then i checked on settings my last automatic antivirus scan, it was 3 weeks before this, the ai script just disguises itself as innocent programs. \n\nI think this is why someone here had it running as 'Alien isolation' game but it's just the AI script phishing your data., BUT it could also be this below:\n\n*I installed alien isolation just to check, and on the file names on alien isolation, it is ABBREVIATED to AI or ai. This is because* ***A***lien ***I***solation *is named as such. Therefore, it is very  likely that with your AMD app, it sees a program named 'ai' - \\[WHICH IS THE ACTUAL MICROSOFT AI\\] and it confuses it with alien isolation as the file directories are abbrevieated and have same name. plus, the AMD app's index of what to call programs, games ect KNOWS ai is supposed to be abbreviation for Alien Isolation, and so it writes any time that another program named ai- like the microsoft ai - was running, as time playing alien isolation.*\n\n&amp;#x200B;\n\non another note:\n\nAlso everyone on dell hardware watch out for Dell DataCollection and Dell DataVault services, also in a month we will get some Dell AiCollection and subsidary services.  Only way i could stop them reinstalling is by removing dell support assist and all its related files manually, then program remover.\n\n&amp;#x200B;\n\n&amp;#x200B;\n\n&amp;#x200B;\n\n&amp;#x200B;\n\nnote that listed filenames might change slightly depending on your windows/office version, and capital/lowercase words vary too.",
  '[removed]'],
 ["Artificial Intelligence is a superset of machine learning. Not all machine learning is neural networks. The meaning is quite different and there are many techniques besides neural networks to solve AI problems. In many cases, it has been found there is significant overlap in the mathematical equivalence of neural network and non-NN techniques. \n\nFrom a policy perspective, solving a problem with a non-NN technique doesn't exempt it from all of the same concerns in AI applications. Limiting policy or discussion to just neural networks also rules out consideration of future techniques that have not yet been developed, which is important, given the speed at which AI technologies are being developed.",
  "Neural networks are a subset of machine learning which is a subset of artificial intelligence - but here's the thing - that only matters to people studying the subjects, laymen just want a simple term to refer to a set of concepts that are relatively similar \n\nand technically AI isn't wrong, you can call all neural networks AI, but not all AI can be a neural network",
  'Business people talk about AI and computer scientists about Deep Learning',
  'It\'s from years ago, but there\'s a saying:\n\n"If it\'s in PowerPoint, it\'s AI. If it\'s in Python, it\'s Machine Learning".',
  '[deleted]',

In [123]:
len(comments), len(items)

(9, 9)

In [124]:
comments_with_url = []
for i in range(len(comments_per_post)):
    for post_comment in comments_per_post[i]:
        comments_with_url.append({ "url": items[i], "comment": post_comment })

len(comments_with_url)

184

In [125]:
import pandas as pd

df = pd.DataFrame(data=comments_with_url)
df

,url,comment
0,https://www.reddit.com/r/Office365/comments/yl...,"Same here, updated after Word was acting ""funn..."
1,https://www.reddit.com/r/Office365/comments/yl...,Ok so I came across this today when I went to ...
2,https://www.reddit.com/r/Office365/comments/yl...,ai.exe: The executable used to host ai.dll. T...
3,https://www.reddit.com/r/Office365/comments/yl...,I deleted the following folder to fix the prob...
4,https://www.reddit.com/r/Office365/comments/yl...,"hey kids, do this, you run one chat gpt from t..."
...,...,...
179,https://www.reddit.com/r/WGU/comments/1fj97ss/...,Has anyone heard what the masters AI/ML capsto...
180,https://www.reddit.com/r/WGU/comments/1fj97ss/...,No wonder WGU is pushing Grammarly so hard rec...
181,https://www.reddit.com/r/WGU/comments/1fj97ss/...,Great. Even more people who dont know shit who...
182,https://www.reddit.com/r/WGU/comments/1fj97ss/...,When you say febuary of next year do you mean ...
183,https://www.reddit.com/r/WGU/comments/1fj97ss/...,Is…is this post written by AI?\n\nBecause it f...

In [128]:
!pip install emoji

Collecting emoji
  Obtaining dependency information for emoji from https://files.pythonhosted.org/packages/91/db/a0335710caaa6d0aebdaa65ad4df789c15d89b7babd9a30277838a7d9aac/emoji-2.14.1-py3-none-any.whl.metadata
  Downloading emoji-2.14.1-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.14.1-py3-none-any.whl (590 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 590.6/590.6 kB 2.6 MB/s eta 0:00:00m eta 0:00:010:01m
Installing collected packages: emoji
Successfully installed emoji-2.14.1

[notice] A new release of pip is available: 23.2.1 -> 25.2
[notice] To update, run: pip install --upgrade pip

In [129]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.stem import PorterStemmer
import emoji

nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('stopwords')

[nltk_data] Downloading package wordnet to /home/julyanna/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /home/julyanna/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /home/julyanna/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [130]:
from pandas.errors import EmptyDataError

try:
  basic_stopwords = list(
    # Handle empty data error
    pd.read_csv('basic_stopwords.txt', header=None).values.flatten()
  )
except EmptyDataError:
  basic_stopwords = []

try:
  domain_stopwords = list(
    pd.read_csv('domain_stopwords.txt', header=None).values.flatten()
  )
except EmptyDataError:
  domain_stopwords = []

def preprocess_text(corpus, text_column='text'):
  cleaned_corpus = corpus.copy()

  # Lowercase
  cleaned_corpus['cleaned_text'] = cleaned_corpus[text_column].str.lower()

  # Lemmatize (by default, lemmatize nouns)
  # Other options:
  #   'v' for verbs
  #   'a' for adjectives
  #   'r' for adverbs
  #   's' for satellites adjectives (adjectives that appear after verbs)
  lemmatizer = WordNetLemmatizer()
  cleaned_corpus['cleaned_text'] = cleaned_corpus['cleaned_text'].apply(
      lambda text: ' '.join(
        [lemmatizer.lemmatize(word, pos='n') for word in text.split()]
      )
  )

  # Stemmer
  stemmer = PorterStemmer()
  cleaned_corpus['cleaned_text'] = cleaned_corpus['cleaned_text'].apply(
      lambda text: ' '.join(
        [stemmer.stem(word) for word in text.split()]
      )
  )

  # Remove NLTK stopwords
  en_stopwords_list = stopwords.words('english')
  cleaned_corpus['cleaned_text'] = cleaned_corpus['cleaned_text'].apply(
    lambda text: ' '.join(
      [
        word for word in text.split() if word not in en_stopwords_list
      ]
    )
  )

  # Remove basic stopwords
  cleaned_corpus['cleaned_text'] = cleaned_corpus['cleaned_text'].apply(
    lambda text: ' '.join(
      [word for word in text.split() if word not in basic_stopwords]
    )
  )

  # Remove domain stopwords
  cleaned_corpus['cleaned_text'] = cleaned_corpus['cleaned_text'].apply(
    lambda text: ' '.join(
      [word for word in text.split() if word not in domain_stopwords]
    )
  )

  # Remove trailing and leading whitespaces
  cleaned_corpus['cleaned_text'] = cleaned_corpus['cleaned_text'].str.strip()

  # Remove non-alphanumeric characters
  cleaned_corpus['cleaned_text'] = cleaned_corpus['cleaned_text'].str.replace(r'\W', ' ', regex=True)

  # Remove numbers
  cleaned_corpus['cleaned_text'] = cleaned_corpus['cleaned_text'].str.replace(r'\d+', ' ', regex=True)

  # Remove emojis using emoji library
  cleaned_corpus['cleaned_text'] = cleaned_corpus['cleaned_text'].apply(
    lambda text: ' '.join(
      [word for word in text.split() if word not in list(emoji.EMOJI_DATA.keys())]
    )
  )

  return cleaned_corpus['cleaned_text']

In [131]:
df['cleaned_text'] = preprocess_text(df, text_column='comment')
df

,url,comment,cleaned_text
0,https://www.reddit.com/r/Office365/comments/yl...,"Same here, updated after Word was acting ""funn...",here updat word wa act funny ms e win h appear...
1,https://www.reddit.com/r/Office365/comments/yl...,Ok so I came across this today when I went to ...,ok came across thi today went add process vpn ...
2,https://www.reddit.com/r/Office365/comments/yl...,ai.exe: The executable used to host ai.dll. T...,ai exe execut use host ai dll thi execut recei...
3,https://www.reddit.com/r/Office365/comments/yl...,I deleted the following folder to fix the prob...,delet follow folder fix problem c program file...
4,https://www.reddit.com/r/Office365/comments/yl...,"hey kids, do this, you run one chat gpt from t...",hey kids this run one chat gpt darkweb run ano...
...,...,...,...
179,https://www.reddit.com/r/WGU/comments/1fj97ss/...,Has anyone heard what the masters AI/ML capsto...,ha anyon heard master ai ml capston like
180,https://www.reddit.com/r/WGU/comments/1fj97ss/...,No wonder WGU is pushing Grammarly so hard rec...,wonder wgu push grammarli hard recently knew l...
181,https://www.reddit.com/r/WGU/comments/1fj97ss/...,Great. Even more people who dont know shit who...,great even peopl dont know shit think know lot...
182,https://www.reddit.com/r/WGU/comments/1fj97ss/...,When you say febuary of next year do you mean ...,say febuari next year mean feb
183,https://www.reddit.com/r/WGU/comments/1fj97ss/...,Is…is this post written by AI?\n\nBecause it f...,is i thi post written ai becaus fuck sound lik...

In [132]:
df.to_csv("redditcomments.csv")